### PR TITLE
Add a render event to customize look of items

### PR DESCRIPTION
**Pull request by stefwalter**
This is a scope event that will be emitted when items are rendered
as elements. The argument will be D3 selection of <g> elements that
correspond to items. Each item has its data set to one of the items.

### CODE REVIEW

**Comment by stefwalter** [comment]
CC @abonas Could you try this out? There's an example in `extra.html` on how to use the render event.

**Comment by abonas** [comment]
> CC @abonas Could you try this out? There's an example in extra.html on how to use the render event.

@stefwalter I sure will, and report back. thank you!

**Comment by stefwalter** [comment]
Rebased.

**Comment by abonas** [comment]
@stefwalter I confirm it works, I was able to customize the content of the tooltip of the graph's elements. so please release this if you can.

**Pull request merged**
