### PR TITLE
assign name attribute if metadata.name is set - for simplicity of input

### PR DESCRIPTION
**Pull request by abonas**

### CODE REVIEW

**Comment by abonas** [comment]
The fix allows more simple input jsons that don't contain the metadata section.
Example:
"542d60fa-e433-11e4-9656-001a4a231290":
{"id":"542d60fa-e433-11e4-9656-001a4a231290","name":"monitoring-influxdb","kind":"Service"}

**Comment by abonas** [comment]
@stefwalter can you review this please? thanks!

**Comment by stefwalter** [comment]
Sorry for the delay. It's a holiday here.
1. I don't understand how this commit affects anything. We don't use the `item.name` anywhere currently. We use `item.metadata.name` as the title when hovering over a vertex, but seems like there's no use of `item.name` either before or after this commit.
2. I would suggest `item.label` as a slightly different concept from the name. An item could have a "label" that is preferred for display, and falls back to display the name (stored in metadata).
3. I've gotten away from modifying items at all in the code, so I would suggest that the caller sets the the label property.
4. Once done, needs documentation update in README.md

**Comment by abonas** [comment]
> Sorry for the delay. It's a holiday here.
> 
> I don't understand how this commit affects anything. We don't use the item.name anywhere currently. We use item.metadata.name as the title when hovering over a vertex, but seems like there's no use of item.name either before or after this commit.
> I would suggest item.label as a slightly different concept from the name. An item could have a "label" that is preferred for display, and falls back to display the name (stored in metadata).
> I've gotten away from modifying items at all in the code, so I would suggest that the caller sets the the label property.
> Once done, needs documentation update in README.md

as discussed, closing the PR, will build metadata section as part of the json.

**Pull request closed without merging**
